// Builds components/sections/process/marks.ts: the real mark of every tool the
// site names, inlined so the page ships no icon library at runtime.
//
// Marks come from two places, in this order:
//   1. public/logos/<slug>.svg — drop an official SVG there to override a mark
//      (useful for products whose owner does not allow redistribution, so no
//      open icon set carries them), then run: node scripts/build-marks.mjs
//   2. the @iconify-json sets installed as devDependencies (logos, devicon)
//
// Tools with no mark of their own (practices, or products without a public
// logo) fall back to a pictogram; see components/sections/process/tools.tsx.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import devicon from "@iconify-json/devicon/icons.json" with { type: "json" };
import logos from "@iconify-json/logos/icons.json" with { type: "json" };

const SETS = { logos, devicon };

/** Tool name as written in messages → icon in one of the sets. */
const MARKS = {
  React: "logos:react",
  "React Native": "logos:react",
  "Next.js": "logos:nextjs-icon",
  "Tailwind CSS": "logos:tailwindcss-icon",
  "Node.js": "logos:nodejs-icon",
  "Spring Boot": "logos:spring-icon",
  "Spring Cloud": "logos:spring-icon",
  PostgreSQL: "logos:postgresql",
  "SQL Server": "devicon:microsoftsqlserver",
  Prisma: "logos:prisma",
  RabbitMQ: "logos:rabbitmq-icon",
  Azure: "logos:azure-icon",
  Docker: "logos:docker-icon",
  "GitHub Actions": "logos:github-actions",
  Linux: "logos:linux-tux",
  TypeScript: "logos:typescript-icon",
  JavaScript: "logos:javascript",
  Java: "logos:java",
  Python: "logos:python",
  "JUnit 5": "devicon:junit",
  Vitest: "logos:vitest",
  Playwright: "logos:playwright",
  JWT: "logos:jwt-icon",
  "OAuth 2.0": "logos:oauth",
  SAP: "logos:sap",
  Jira: "logos:jira",
  // Microsoft does not license its product marks to open icon sets: the
  // company mark stands in until an official file is dropped in public/logos.
  "Microsoft Graph": "logos:microsoft-icon",
  "Copilot Studio": "logos:microsoft-icon",
};

const slug = (name) =>
  name
    .toLowerCase()
    .replaceAll("+", "plus")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

function fromSet(id) {
  const [setName, iconName] = id.split(":");
  const set = SETS[setName];
  const icon = set?.icons[iconName];
  if (!icon) throw new Error(`unknown icon ${id}`);
  const width = icon.width ?? set.width ?? 24;
  const height = icon.height ?? set.height ?? 24;
  return { body: icon.body, viewBox: `0 0 ${width} ${height}` };
}

/** An SVG file dropped in public/logos, reduced to what goes inside <svg>. */
function fromFile(file) {
  const source = readFileSync(join("public/logos", file), "utf8");
  const viewBox = source.match(/viewBox="([^"]+)"/)?.[1];
  const width = source.match(/\swidth="([\d.]+)"/)?.[1];
  const height = source.match(/\sheight="([\d.]+)"/)?.[1];
  const body = source.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>[\s\S]*$/, "");
  return { body: body.trim(), viewBox: viewBox ?? `0 0 ${width ?? 24} ${height ?? 24}` };
}

const overrides = new Map();
try {
  for (const file of readdirSync("public/logos")) {
    if (file.endsWith(".svg")) overrides.set(file.slice(0, -4), file);
  }
} catch {
  // No overrides yet.
}

const entries = Object.entries(MARKS).map(([name, id]) => {
  const override = overrides.get(slug(name));
  return [name, override ? fromFile(override) : fromSet(id)];
});

const file = `// Generated by scripts/build-marks.mjs — do not edit by hand.
// Each mark is the tool's own logo, inlined as the inside of an <svg>.

export type Mark = { body: string; viewBox: string };

export const MARKS: Record<string, Mark> = ${JSON.stringify(Object.fromEntries(entries), null, 2)};
`;

writeFileSync("components/sections/process/marks.ts", file);
console.log(`wrote ${entries.length} marks (${overrides.size} from public/logos)`);
